version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
skip_commits:
  files:
  - doc/*
  - README.md
  - .vsts-ci.yml
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
  TreatWarningsAsErrors: true
before_build:
- |- # Restore TWICE. See https://github.com/AArnott/Nerdbank.GitVersioning/issues/113#issuecomment-285903085
  msbuild src\Microsoft.VisualStudio.Composition.sln /nologo /m /v:quiet /t:restore > nul
  msbuild src\Microsoft.VisualStudio.Composition.sln /nologo /m /v:quiet /t:restore
build_script:
- ps: msbuild src\Microsoft.VisualStudio.Composition.sln /nologo /m /v:minimal /t:build,pack
test_script:
- cmd: >-
    SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%

    pip install codecov

    SET testdir=bin\Tests\%configuration%\net452\

    "%userprofile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"
    -register:user
    -target:"%xunit20%\xunit.console.x86.exe"
    -targetargs:"%testdir%Microsoft.VisualStudio.Composition.Tests.dll -noshadow -html %testdir%testresults.html -xml %testdir%testresults.xml -appveyor -notrait TestCategory=FailsInCloudTest -nologo -parallel none"
    -returntargetcode
    -excludebyattribute:*.ExcludeFromCodeCoverage*
    -excludebyfile:*\*Designer.cs
    -filter:"+[Microsoft.VisualStudio.Composition]*"
    -hideskipped:All
    -output:%testdir%code_coverage.xml

    codecov -f "%testdir%code_coverage.xml"

    SET testdir=bin\Tests\%configuration%\net46\

    "%userprofile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"
    -register:user
    -target:"%xunit20%\xunit.console.x86.exe"
    -targetargs:"%testdir%Microsoft.VisualStudio.Composition.Tests.dll -noshadow -html %testdir%testresults.html -xml %testdir%testresults.xml -appveyor -notrait TestCategory=FailsInCloudTest -nologo -parallel none"
    -returntargetcode
    -excludebyattribute:*.ExcludeFromCodeCoverage*
    -excludebyfile:*\*Designer.cs
    -filter:"+[Microsoft.VisualStudio.Composition]*"
    -hideskipped:All
    -output:%testdir%code_coverage.xml

    codecov -f "%testdir%code_coverage.xml"

    cd src\tests\Microsoft.VisualStudio.Composition.Tests

    dotnet test -f netcoreapp1.0 --no-build
artifacts:
- path: bin\%configuration%\Packages\Microsoft.VisualStudio.Composition.15.*.nupkg
  name: NuGet Package
- path: bin\%configuration%\Packages\Microsoft.VisualStudio.Composition.AppHost.15.*.nupkg
  name: NuGet Package
